language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
script: bundle exec rake ci
gemfile:
  - Gemfile
  - gemfiles/Gemfile.puppet-3.0.2
  - gemfiles/Gemfile.puppet-3.1.1
  - gemfiles/Gemfile.puppet-3.2.0.rc
matrix:
  allow_failures:
    - gemfile: gemfiles/Gemfile.puppet-3.2.0.rc
    - rvm: 2.0.0
notifications:
  email:
    - dev@endore.me
